### ISSUE TITLE
Start Failure

### ISSUE THREAD

**Issue by potspinal** [FarmBot-Labs/farmbot-web-frontend#222]
When  I run node start I found an error below, Please help me

ERROR in multi (webpack)-dev-server/client?http://0.0.0.0:8082 ./src/front_page/index.tsx
Module not found: Error: Can't resolve './src/front_page/index.tsx' in '/home/pi/farmbot-web-frontend'
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8082 ./src/front_page/index.tsx

ERROR in multi (webpack)-dev-server/client?http://0.0.0.0:8082 ./src/password_reset/index.tsx
Module not found: Error: Can't resolve './src/password_reset/index.tsx' in '/home/pi/farmbot-web-fronten
d'
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8082 ./src/password_reset/index.tsx

ERROR in multi (webpack)-dev-server/client?http://0.0.0.0:8082 ./src/tos_update/index.tsx
Module not found: Error: Can't resolve './src/tos_update/index.tsx' in '/home/pi/farmbot-web-frontend'
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8082 ./src/tos_update/index.tsx

ERROR in multi (webpack)-dev-server/client?http://0.0.0.0:8082 ./src/verification.ts
Module not found: Error: Can't resolve './src/verification.ts' in '/home/pi/farmbot-web-frontend'
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8082 ./src/verification.ts

ERROR in multi (webpack)-dev-server/client?http://0.0.0.0:8082 ./src/entry.tsx
Module not found: Error: Can't resolve '/home/pi/farmbot-web-frontend/src/entry.tsx' in '/home/pi/farmbo
t-web-frontend'
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8082 ./src/entry.tsx

**Comment by RickCarlino** [comment]
@potspinal This repository is no longer used. We keep it online for historical purposes and reference only. Please uninstall it and start over with the setup instructions for the new app [here](https://github.com/FarmBot/Farmbot-Web-App).
